package by.epam.tr.cg.command;

public enum CommandName {
	ADD_PRODUCT, DELETE_PRODUCT_BY_ID, UPDATE_PRODUCT_BY_ID, SHOW_ALL_PRODUCTS, SHOW_PRODUCTS_BY_CATEGORY, SHOW_COUNT_MIN_MAX_PRICE_FOR_CATEGORY
}
